# -*- mode: ruby -*-
# vi: set ft=ruby :

load File.expand_path('../BaseVagrantfile', File.dirname(__FILE__))

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "mw-ubuntu1604-base"

  config.vm.provider "virtualbox" do |vb|
    # GUIを使う時はtrue
    vb.gui = false
    vb.name = "vb-mw-ubuntu1604-base"
  end
end


if File.file?('Vagrantfile.local') then
    load 'Vagrantfile.local'
end
