---
- name: install zsh
  become: 'yes'
  apt: name=zsh state=latest

# zshのプラグインマネージャ
- name: install zplug
  become: 'no'
  # https://github.com/zplug/zplug/blob/master/doc/guide/ja/README.md
  shell: |
      curl -sL --proto-redir -all,https \
      https://raw.githubusercontent.com/zplug/installer/master/installer.zsh \
      | zsh
  args:
    chdir: "/home/{{ ansible_ssh_user }}"
    creates: "/home/{{ ansible_ssh_user }}/.zplug"
