- hosts: all
  roles:
    - bootstrap
    - vcs
    - vim
    - core_utils
    - cmake
    - zsh
    - tmux
    - ninja
    - apt_utils
    - c++_utils
    - lubuntu
    - gui_utils
    - qt5_dev
    - pyqt5
    - python_extra
    - nfs_server
