# -*- mode: ruby -*-
# vi: set ft=ruby :

load File.expand_path('../BaseVagrantfile', File.dirname(__FILE__))

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "mw-ubuntu1604-dev"

  config.vm.provider "virtualbox" do |vb|
    # GUIを使う時はtrue
    vb.gui = false

    vb.name = "vb-mw-ubuntu1604-dev"

    # 仮想マシンに割り当てるメモリサイズ[MByte]
    vb.memory = "4098"

    # 割りあてるコア数
    vb.customize ["modifyvm", :id, "--cpus", "4", "--ioapic", "on"]
  end
end
