---
- name: add a repository for ansible
  become: 'yes'
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present

- name: install ansible
  become: 'yes'
  apt: name={{ item }} state=present
  with_items:
    - ansible
