# -*- mode: ruby -*-
# vi: set ft=ruby :

load File.expand_path('../BaseVagrantfile', File.dirname(__FILE__))

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "mw-ubuntu1604-gui-dev"

  config.vm.provider "virtualbox" do |vb|
    # GUIを使う時はtrue
    vb.gui = true

    vb.name = "vb-mw-ubuntu1604-gui-dev"

    # 仮想マシンに割り当てるメモリサイズ[MByte]
    vb.memory = "6144"

    # 割りあてるコア数
    vb.customize ["modifyvm", :id, "--cpus", "4", "--ioapic", "on"]

    # ビデオメモリー(MB)
    vb.customize ["modifyvm", :id, "--vram"  , "128"]
  end
end


if File.file?('Vagrantfile.local') then
    load 'Vagrantfile.local'
end
