- name: install c++utils
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - exuberant-ctags
    - cscope
    - ccache
    - clang
    - libclang-dev

# libclang.soはVimのプラグインとか拡張系でよく使われる。標準的なパスにシンボ
# リックリンクを作成しておいた方が扱いやすい
- name: mklink libclang.so
  become: yes
  shell: |
      ln -s /usr/lib/llvm-3.8/lib/libclang.so /usr/lib/libclang.so
  args:
    creates: /usr/lib/libclang.so
