---
- hosts: all
  roles:
    - bootstrap
    - apt_utils
    - pip
    - ansible
    - git
    - vcs
    - core_utils
    - linter
    - vcs
    - build_core
    - vim
    - cmake
    - zsh
    - tmux
    - ninja
    - c++_utils
    - python_extra
    - nfs_server
    - nodejs
    - golang
