- name: installing a package to build Ninja
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - re2c

- name: download Ninja source code
  become: yes
  git:
    repo: https://github.com/ninja-build/ninja.git
    dest: /usr/local/src/ninja
    update: no
    depth: 1
  register: download_ninja

- name: build and install Ninja
  become: yes
  shell: |
    ./configure.py  --bootstrap
    cp ninja /usr/local/bin
  args:
    chdir: /usr/local/src/ninja
    creates: /usr/local/bin/ninja
  when: download_ninja|success
