- name: install gui_core
  become: yes
  apt: name={{ item }} state=present
  with_items:
    # https://github.com/openai/gym/issues/509
    # https://stackoverflow.com/questions/18406369/qt-cant-find-lgl-error
    - mesa-utils
    - libgl1-mesa-glx
    - libgl1-mesa-dev
