---
- name: install tmux
  become: 'yes'
  apt: name=tmux state=latest

# tmuxのプラグインマネージャ
- name: install tpm
  become: 'no'
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ ansible_ssh_user }}/.tmux/plugins/tpm"
    update: 'no'
    depth: 1
