---
- name: add a repository for git
  become: 'yes'
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present

- name: install git
  become: 'yes'
  apt: name={{ item }} state=present
  with_items:
    - git
