- name: install core_utils
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - unzip
    - curl
    - wget
    - imagemagick
    - nkf
    # SSH時にX11Forwardingでコピペできるようにするため
    - xclip
    - xsel
    # ネットワークデバッグ用
    - nmap
    - netcat
    # manの拡張
    - manpages-dev
    - manpages-ja
    - manpages-ja-dev
    # アプリケーションをソースからビルドする際に、この辺のパッケージはよく必要になる
    - libtiff5-dev
    - libjpeg8-dev
    - libfreetype6-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libxmu-dev
    - libxpm-dev
    - libevent-dev
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - pkg-config
    - flex
    - gperf
    - bison
    - help2man
    - texinfo
